// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKUUBA22GhbPY_0hegrujn8jjDsv37TI',
    appId: '1:477921190502:web:73ab5ad0da5b0af4f303a7',
    messagingSenderId: '477921190502',
    projectId: 'voyage-bd63e',
    authDomain: 'voyage-bd63e.firebaseapp.com',
    storageBucket: 'voyage-bd63e.firebasestorage.app',
    databaseURL: 'https://voyage-bd63e-default-rtdb.firebaseio.com', // Ajouté
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-qeE0JLeezELUQARo0f7HtYP5xgbdZ4',
    appId: '1:477921190502:android:804b32dcaf491dabf303a7',
    messagingSenderId: '477921190502',
    projectId: 'voyage-bd63e',
    storageBucket: 'voyage-bd63e.firebasestorage.app',
    databaseURL: 'https://voyage-bd63e-default-rtdb.firebaseio.com', // Ajouté
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0P9jfmHoqhG_TNve7MD_Xe2mgshAwZfg',
    appId: '1:477921190502:ios:2062ae6f6bf0fac6f303a7',
    messagingSenderId: '477921190502',
    projectId: 'voyage-bd63e',
    storageBucket: 'voyage-bd63e.firebasestorage.app',
    iosBundleId: 'com.voyage.voyage',
    databaseURL: 'https://voyage-bd63e-default-rtdb.firebaseio.com', // Ajouté
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0P9jfmHoqhG_TNve7MD_Xe2mgshAwZfg',
    appId: '1:477921190502:ios:2062ae6f6bf0fac6f303a7',
    messagingSenderId: '477921190502',
    projectId: 'voyage-bd63e',
    storageBucket: 'voyage-bd63e.firebasestorage.app',
    iosBundleId: 'com.voyage.voyage',
    databaseURL: 'https://voyage-bd63e-default-rtdb.firebaseio.com', // Ajouté
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsKUUBA22GhbPY_0hegrujn8jjDsv37TI',
    appId: '1:477921190502:web:659425280f08a518f303a7',
    messagingSenderId: '477921190502',
    projectId: 'voyage-bd63e',
    authDomain: 'voyage-bd63e.firebaseapp.com',
    storageBucket: 'voyage-bd63e.firebasestorage.app',
    databaseURL: 'https://voyage-bd63e-default-rtdb.firebaseio.com', // Ajouté
  );
}